### PR TITLE
Initial support for OpenAPI 3.0

### PR DESCRIPTION
**Pull request by sprootshift**
This pull request adds initial support for OpenAPI 3.0. 

enjoi dependency is a placeholder to be updated later if/when https://github.com/tlivings/enjoi/pull/92 is merged.

### CODE REVIEW

**Comment by tlivings** [comment]
Also have #183 PR...

**Comment by sprootshift** [comment]
My understanding is that https://github.com/krakenjs/hapi-openapi/pull/181 is a very different approach. It is more of a refactoring of the library to abstract away the details of Swagger and OpenAPI3 schema into a single proxy object. I am not sure how much of it is really needed, given that `swagger-parser` does a decent job parsing both. In my approach I am working directly with `swagger-parser` output and it seems to work reasonably well. But if you think there is value in the intermediate proxy representation of `swagger-parser` output, I think it can be merged into this PR.

**Comment by sprootshift** [comment]
@tlivings So what's your view of these PRs? Is it something you consider to merge?

**Comment by tlivings** [comment]
I am trying to get to this today. Been slammed and distracted by day job.

**Comment by sprootshift** [comment]
Thanks for merging it. Could you please publish enjoi first and then this, after I update dependency to npm enjoi?

**Pull request merged**
