### PR TITLE
add package-lock file

### PR DESCRIPTION
**Pull request by dcharbonnier**
https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json

2021 : _This file is intended to be committed into source repositories_

### CODE REVIEW

**Comment by dcharbonnier** [comment]
if you merge the previous one (#190)  @tlivings this one should be ok, if you reject the other one I will remove the other commit

**Comment by tlivings** [comment]
Do we want to base this off latest so it doesn't include security changes?

**Comment by tlivings** [comment]
Also, I don't really like using lockfiles for modules

**Comment by dcharbonnier** [comment]
As you want, it's just Impossible to reproduce the "state" of this module without this file. But not a big deal.

**Pull request closed without merging**
